/* Create Tables */
DROP TABLE IF EXISTS BLOGS;
CREATE TABLE BLOGS
(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(256) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    MODIFIED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ARTICLES;
CREATE TABLE ARTICLES
(
	ID INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(256) NOT NULL,
	CONTENT TEXT,
	CREATED_AT TIMESTAMP DEFAULT NOW(),
	MODIFIED_AT TIMESTAMP,
    POSTED_AT TIMESTAMP,
	BLOG_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (BLOG_ID) REFERENCES BLOGS (ID)
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS
(
    ID INT NOT NULL AUTO_INCREMENT,
    CONTENT TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    MODIFIED_AT TIMESTAMP,
    ARTICLE_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID)
);

DROP TABLE IF EXISTS TAGS;
CREATE TABLE TAGS
(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(256) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    MODIFIED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ARTICLE_TAG;
CREATE TABLE ARTICLE_TAG
(
	ID INT NOT NULL AUTO_INCREMENT,
	ARTICLE_ID INT NOT NULL,
	TAG_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID),
	FOREIGN KEY (TAG_ID) REFERENCES TAGS (ID)
);